#!/bin/bash
#

set AUDIODEV=hw:1

DECODER=wsprcan/k9an-wsprd
TMPOUT='_wsprd.out'

echo "configuring i2c"
/home/debian/final/i2c/./si5351
i=0


echo 115 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio115/direction
echo 0 > /sys/class/gpio/gpio115/value

decode () {
	#paplay /home/debian/final/data/iq-16b.wav&

	if ((i == 0)); then
		echo 0 > /sys/class/gpio/gpio115/value
		date >> /home/debian/final/relaystatus.log
		echo "BP enabled" >> /home/debian/final/relaystatus.log
		echo "done"

	elif ((i == 1)); then
		echo 1 > /sys/class/gpio/gpio115/value
		date >> /home/debian/final/relaystatus.log
		echo "RF enabled" >> /home/debian/final/relaystatus.log
		echo "done"

	fi
}

while true
do
	sec=$(date +'%S')
	min=$(date +'%M')
	#date
	if (("10#$min" % 10 == 0 && "10#$sec" == 0 )); then
		echo -n "flipping relay "
		((i = !i))
		decode
	fi
done
