#!/bin/bash
#

set AUDIODEV=hw:1

DECODER=wsprcan/k9an-wsprd
TMPOUT='_wsprd.out'
#export XDG_RUNTIME_DIR="/run/user/1000"
#fix simple() permission denied
pax11publish -d
pax11publish -r
##
pactl unload-module module-loopback
aplay -l
echo "enabling loopback"
pactl load-module module-loopback source=alsa_input.usb-Plugable_Plugable_USB_Audio_Device_000000000000-00.analog-stereo

echo "configuring i2c"
/home/debian/final/i2c/./si5351
i=0
j=0

decode () {
	#paplay /home/debian/final/data/iq-16b.wav&
	((i++))

	if ((i == 0)); then
		echo "BP enabled"
		date
		date >> /home/debian/final/RFoutput.log
		/home/debian/final/wsprcan/./k9an-wsprd >> /home/debian/final/RFoutput.log

	elif ((i == 1)); then
		echo "RF enabled"
		date
		date >> /home/debian/final/BPoutput.log
		/home/debian/final2/wsprcan/./k9an-wsprd >> /home/debian/final/BPoutput.log
}

decode2(){}

while true
do
	sec=$(date +'%S')
	min=$(date +'%M')
	if (("10#$min" % 10 == 0 && "10#$sec" == 0 )); then
		echo "10mins?"
		date
		((i=!i))
	if (("10#$min" % 2 == 0 && "10#$sec" == 0 )); then
		echo -n "Executing wspr_decode "
			decode
	fi
done
