#!/bin/bash
#

set AUDIODEV=hw:1

DECODER=wsprcan/k9an-wsprd
TMPOUT='_wsprd.out'
export XDG_RUNTIME_DIR="/run/user/$(id -u)"
#fix simple() permission denied
pax11publish -d
pax11publish -r
##

sleep 5
aplay -l

echo "enabling loopback"
pactl load-module module-loopback source=alsa_input.usb-Plugable_Plugable_USB_Audio_Device_000000000000-00.analog-stereo

echo "configuring i2c"
/home/debian/final/i2c/./si5351

decode () {
	paplay /home/debian/final/data/iq-16b.wav&
	date
	date >> /home/debian/final/wsproutput.log
	/home/debian/final/wsprcan/./k9an-wsprd  >> /home/debian/final/wsproutput.log

}

while true
do
	sec=$(date +'%S')
	min=$(date +'%M')

	if (("10#$min" % 2 == 0 && "10#$sec" == 0 )); then
		echo -n "Executing wspr_decode "
		decode
	elif ((10#$sec < 40)); then
		sleep 1
	fi
done
